-- Campus Maintenance Portal
-- Run this script in the Supabase SQL Editor.

create table if not exists public.users (
    id bigint generated by default as identity primary key,
    name varchar(100) not null,
    email varchar(150) unique not null,
    password text not null,
    role varchar(20) not null default 'student'
        check (role in ('student', 'admin')),
    created_at timestamptz not null default now()
);

create table if not exists public.maintenance_requests (
    id bigint generated by default as identity primary key,
    student_id bigint not null references public.users(id) on delete cascade,
    title varchar(150) not null,
    description text not null,
    category varchar(50) not null,
    location varchar(150) not null,
    status varchar(30) not null default 'Pending'
        check (status in ('Pending', 'Approved', 'Assigned', 'In Progress', 'Completed', 'Rejected')),
    assigned_to varchar(100),
    admin_comment text default '',
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index if not exists idx_requests_student
on public.maintenance_requests(student_id);

create index if not exists idx_requests_status
on public.maintenance_requests(status);

create index if not exists idx_requests_created
on public.maintenance_requests(created_at desc);

-- Demo admin.
-- Password: Admin@123
insert into public.users (name, email, password, role)
select
    'Campus Administrator',
    'admin@campus.com',
    'scrypt:32768:8:1$demo$6c4e1c0d8cba8e0d2d1a9c6d5f9f2f5a0c5f4f6e0e1a7b3b7e7e9c5f4a3c2d1',
    'admin'
where not exists (
    select 1 from public.users where email = 'admin@campus.com'
);

-- IMPORTANT:
-- The demo hash above is intentionally not used by the application.
-- For a guaranteed working admin account, use the /register route to create a
-- student first, then change that user's role to admin in Supabase:
--
-- update public.users set role='admin' where email='your-email@example.com';
--
-- This avoids storing a password hash that may differ between Werkzeug versions.

-- Optional: enable Row Level Security only if you later replace the server-side
-- Supabase key with a proper RLS/JWT architecture. This Flask version performs
-- authorization on the server, so do not enable restrictive RLS policies without
-- also designing policies for the server key you use.
